apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: intent-classification
spec:
  predictor:
    containers:
      - name: kserve-container
        image: mariaponomarenko/kserve-app:latest