name: homework-2

on:
  pull_request:
    branches:
      - main

env:
  IMAGE_ML_APP: app_ml
  IMAGE_WEB_APP: app_web
  IMAGE_MINIO: minio-client
  IMAGE_MINIO_FOLDER: minio_deployment

jobs:
  build-and-push-app-ml:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 
        uses: actions/checkout@v2

      - name: Login 
        run: |
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Build 
        run: |
          docker build --tag ${{ secrets.DOCKER_USERNAME }}/${{ env.IMAGE_ML_APP }}:latest ./${{ env.IMAGE_ML_APP }}
      - name: Push 
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/${{ env.IMAGE_ML_APP }}:latest

  build-and-push-app-web:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 
        uses: actions/checkout@v2

      - name: Login 
        run: |
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Build 
        run: |
          docker build --tag ${{ secrets.DOCKER_USERNAME }}/${{ env.IMAGE_WEB_APP }}:latest ./${{ env.IMAGE_WEB_APP }}
      - name: Push 
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/${{ env.IMAGE_WEB_APP }}:latest

  k8s-test-deployment-action:
    runs-on: ubuntu-latest
    steps:
      - name: Create k8s Kind Cluster
        uses: helm/kind-action@v1.4.0

      - name: Checkout 
        uses: actions/checkout@v2

      - name: Deploy application
        run: |
          kubectl create -f k8s_resources/deployment-app-web.yml
      - name: Print pods
        run: |
          sleep 5 && kubectl get pod -A
      - name: Run test
        run: |
          sleep 5 && kubectl wait --for=condition=available --timeout=300s deployment/deployments-app-web
      - name: Print pods
        run: |
          sleep 5 && kubectl get pod -A

  k8s-test-job-cli:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Install and configure KinD
        run: |
          GO111MODULE="on" go get sigs.k8s.io/kind@v0.11.1
          sudo mv $(go env GOPATH)/bin/kind /usr/local/bin/
          kind create cluster
      - name: Set up kubectl
        run: |
          kubectl cluster-info
          kubectl config use-context kind-kind
      - name: Deploy application
        run: |
          kubectl create -f k8s_resources/job-app-ml.yml
      - name: Print pods
        run: |
          sleep 5 && kubectl get pod -A
      - name: Run test
        run: |
          sleep 5 && kubectl wait --for=condition=complete --timeout=300s job/job-app-ml
      - name: Print pods
        run: |
          sleep 5 && kubectl get pod -A
      - name: Clean up
        run: |
          kind delete cluster