name: homework-2

on:
  pull_request:
    branches:
      - main

env:
  IMAGE_ML_APP: app_ml
  IMAGE_WEB_APP: app_web


jobs:
  build-and-push-app-ml:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 
        uses: actions/checkout@v2

      - name: Login 
        run: |
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Build 
        run: |
          docker build --tag ${{ secrets.DOCKER_USERNAME }}/${{ env.IMAGE_ML_APP }}:latest ./${{ env.IMAGE_ML_APP }}
      - name: Push 
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/${{ env.IMAGE_ML_APP }}:latest
      - name: Run ok
        run: |
          docker run --rm --name app-ml-test-run ${{ secrets.DOCKER_USERNAME }}/${{ env.IMAGE_ML_APP }}:latest

  build-and-push-app-web:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 
        uses: actions/checkout@v2

      - name: Login 
        run: |
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Build 
        run: |
          docker build --tag ${{ secrets.DOCKER_USERNAME }}/${{ env.IMAGE_WEB_APP }}:latest ./${{ env.IMAGE_WEB_APP }}
      - name: Push 
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/${{ env.IMAGE_WEB_APP }}:latest
      - name: Run ok
        run: |
          docker run --rm --name app-web-test-run ${{ secrets.DOCKER_USERNAME }}/${{ env.IMAGE_WEB_APP }}:latest