name: homework-2

on:
  pull_request:
    branches:
      - model-train

env:
  IMAGE_ML_APP: image-classification

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 
        uses: actions/checkout@v2

      - name: Login 
        run: |
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Build 
        run: |
          docker build --tag ${{ secrets.DOCKER_USERNAME }}/${{ env.IMAGE_ML_APP }}:latest ./${{ env.IMAGE_ML_APP }}
      - name: Test code
        run: |
          docker run ${{ secrets.DOCKER_USERNAME }}/${{ env.IMAGE_ML_APP }}:latest pytest --disable-warnings -rc test_code.py
      - name: Test data
        run: |
          docker run ${{ secrets.DOCKER_USERNAME }}/${{ env.IMAGE_ML_APP }}:latest pytest --disable-warnings -rc test_data.py
      - name: Test model
        run: |
          docker run ${{ secrets.DOCKER_USERNAME }}/${{ env.IMAGE_ML_APP }}:latest pytest --disable-warnings -rc test_model.py
      - name: Push 
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/${{ env.IMAGE_ML_APP }}:latest

  